// Objective-C API for talking to github.com/seald/go-seald-sdk/mobile_sdk Go package.
//   gobind -lang=objc -prefix="SealdSdkInternals" github.com/seald/go-seald-sdk/mobile_sdk
//
// File is generated by gobind. Do not edit.

#ifndef __SealdSdkInternalsMobile_sdk_H__
#define __SealdSdkInternalsMobile_sdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SealdSdkInternalsMobile_sdkAccountInfo;
@class SealdSdkInternalsMobile_sdkActionStatus;
@class SealdSdkInternalsMobile_sdkActionStatusArray;
@class SealdSdkInternalsMobile_sdkAuthFactor;
@class SealdSdkInternalsMobile_sdkCheckSigchainResponse;
@class SealdSdkInternalsMobile_sdkClearFile;
@class SealdSdkInternalsMobile_sdkConnector;
@class SealdSdkInternalsMobile_sdkConnectorTypeValue;
@class SealdSdkInternalsMobile_sdkConnectorTypeValueArray;
@class SealdSdkInternalsMobile_sdkConnectorsArray;
@class SealdSdkInternalsMobile_sdkConvertTmrAccessesResponse;
@class SealdSdkInternalsMobile_sdkCreateAccountOptions;
@class SealdSdkInternalsMobile_sdkCreateSubIdentityOptions;
@class SealdSdkInternalsMobile_sdkCreateSubIdentityResponse;
@class SealdSdkInternalsMobile_sdkDeviceMissingKeys;
@class SealdSdkInternalsMobile_sdkDevicesMissingKeysArray;
@class SealdSdkInternalsMobile_sdkEncryptionSessionRetrievalDetails;
@class SealdSdkInternalsMobile_sdkGetFactorTokenResponse;
@class SealdSdkInternalsMobile_sdkGetSigchainResponse;
@class SealdSdkInternalsMobile_sdkGroupTMRTemporaryKey;
@class SealdSdkInternalsMobile_sdkGroupTMRTemporaryKeyArray;
@class SealdSdkInternalsMobile_sdkListedGroupTMRTemporaryKeys;
@class SealdSdkInternalsMobile_sdkMassReencryptOptions;
@class SealdSdkInternalsMobile_sdkMassReencryptResponse;
@class SealdSdkInternalsMobile_sdkMobileEncryptionSession;
@class SealdSdkInternalsMobile_sdkMobileEncryptionSessionArray;
@class SealdSdkInternalsMobile_sdkMobileSDK;
@class SealdSdkInternalsMobile_sdkMobileSSKSPassword;
@class SealdSdkInternalsMobile_sdkMobileSSKSTMR;
@class SealdSdkInternalsMobile_sdkPreGeneratedKeys;
@class SealdSdkInternalsMobile_sdkPreValidationToken;
@class SealdSdkInternalsMobile_sdkRecipientRights;
@class SealdSdkInternalsMobile_sdkRecipientWithRights;
@class SealdSdkInternalsMobile_sdkRecipientsWithRightsArray;
@class SealdSdkInternalsMobile_sdkRenewKeysOptions;
@class SealdSdkInternalsMobile_sdkRetrieveIdentityResponse;
@class SealdSdkInternalsMobile_sdkRevokeResult;
@class SealdSdkInternalsMobile_sdkSaveIdentityResponse;
@class SealdSdkInternalsMobile_sdkSdkInitializeOptions;
@class SealdSdkInternalsMobile_sdkSearchGroupTMRTemporaryKeysOpts;
@class SealdSdkInternalsMobile_sdkSsksPasswordInitializeOptions;
@class SealdSdkInternalsMobile_sdkSsksTMRInitializeOptions;
@class SealdSdkInternalsMobile_sdkStringArray;
@class SealdSdkInternalsMobile_sdkTmrAccessesConvertFilters;
@class SealdSdkInternalsMobile_sdkTmrAccessesRetrievalFilters;
@class SealdSdkInternalsMobile_sdkTmrRecipientWithRights;
@class SealdSdkInternalsMobile_sdkTmrRecipientWithRightsArray;

@interface SealdSdkInternalsMobile_sdkAccountInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull userId;
@property (nonatomic) NSString* _Nonnull deviceId;
@property (nonatomic) int64_t deviceExpires;
@end

@interface SealdSdkInternalsMobile_sdkActionStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) BOOL success;
@property (nonatomic) NSString* _Nonnull errorCode;
@property (nonatomic) NSString* _Nonnull result;
@end

@interface SealdSdkInternalsMobile_sdkActionStatusArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkActionStatusArray* _Nullable)add:(SealdSdkInternalsMobile_sdkActionStatus* _Nullable)s;
- (SealdSdkInternalsMobile_sdkActionStatus* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkAuthFactor : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface SealdSdkInternalsMobile_sdkCheckSigchainResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL found;
@property (nonatomic) long position;
@property (nonatomic) long lastPosition;
@end

@interface SealdSdkInternalsMobile_sdkClearFile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull filename;
@property (nonatomic) NSString* _Nonnull sessionId;
@property (nonatomic) NSData* _Nullable fileContent;
@end

@interface SealdSdkInternalsMobile_sdkConnector : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull sealdId;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) NSString* _Nonnull value;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull state;
@end

@interface SealdSdkInternalsMobile_sdkConnectorTypeValue : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) NSString* _Nonnull value;
@end

@interface SealdSdkInternalsMobile_sdkConnectorTypeValueArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkConnectorTypeValueArray* _Nullable)add:(SealdSdkInternalsMobile_sdkConnectorTypeValue* _Nullable)s;
- (SealdSdkInternalsMobile_sdkConnectorTypeValue* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkConnectorsArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkConnectorsArray* _Nullable)add:(SealdSdkInternalsMobile_sdkConnector* _Nullable)s;
- (SealdSdkInternalsMobile_sdkConnector* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkConvertTmrAccessesResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull status;
@property (nonatomic) SealdSdkInternalsMobile_sdkStringArray* _Nullable converted;
@property (nonatomic) long errored;
@property (nonatomic) long succeeded;
@end

@interface SealdSdkInternalsMobile_sdkCreateAccountOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull displayName;
@property (nonatomic) NSString* _Nonnull deviceName;
@property (nonatomic) NSString* _Nonnull signupJWT;
@property (nonatomic) int64_t expireAfter;
@property (nonatomic) SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable preGeneratedKeys;
@end

@interface SealdSdkInternalsMobile_sdkCreateSubIdentityOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull deviceName;
@property (nonatomic) int64_t expireAfter;
@property (nonatomic) SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable preGeneratedKeys;
@end

@interface SealdSdkInternalsMobile_sdkCreateSubIdentityResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull deviceId;
@property (nonatomic) NSData* _Nullable backupKey;
@end

@interface SealdSdkInternalsMobile_sdkDeviceMissingKeys : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull deviceId;
@end

@interface SealdSdkInternalsMobile_sdkDevicesMissingKeysArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkDeviceMissingKeys* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkEncryptionSessionRetrievalDetails : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long flow;
@property (nonatomic) NSString* _Nonnull groupId;
@property (nonatomic) NSString* _Nonnull proxySessionId;
@property (nonatomic) BOOL fromCache;
@end

@interface SealdSdkInternalsMobile_sdkGetFactorTokenResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull token;
@property (nonatomic) NSString* _Nonnull authenticatedSessionId;
@end

@interface SealdSdkInternalsMobile_sdkGetSigchainResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull hash;
@property (nonatomic) long position;
@end

@interface SealdSdkInternalsMobile_sdkGroupTMRTemporaryKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyId;
@property (nonatomic) NSString* _Nonnull groupId;
@property (nonatomic) int64_t created;
@property (nonatomic) BOOL isAdmin;
@property (nonatomic) NSString* _Nonnull createdById;
@property (nonatomic) NSString* _Nonnull authFactorType;
@end

@interface SealdSdkInternalsMobile_sdkGroupTMRTemporaryKeyArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method GroupTMRTemporaryKeyArray.Add with unsupported parameter or return types

- (SealdSdkInternalsMobile_sdkGroupTMRTemporaryKey* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkListedGroupTMRTemporaryKeys : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long nbPage;
@property (nonatomic) SealdSdkInternalsMobile_sdkGroupTMRTemporaryKeyArray* _Nullable keys;
@end

@interface SealdSdkInternalsMobile_sdkMassReencryptOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long retries;
@property (nonatomic) long retrieveBatchSize;
@property (nonatomic) int64_t waitBetweenRetries;
@property (nonatomic) BOOL waitProvisioning;
@property (nonatomic) int64_t waitProvisioningTime;
@property (nonatomic) int64_t waitProvisioningTimeMax;
@property (nonatomic) int64_t waitProvisioningTimeStep;
@property (nonatomic) long waitProvisioningRetries;
@property (nonatomic) BOOL forceLocalAccountUpdate;
@end

@interface SealdSdkInternalsMobile_sdkMassReencryptResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long reencrypted;
@property (nonatomic) long failed;
@end

@interface SealdSdkInternalsMobile_sdkMobileEncryptionSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) SealdSdkInternalsMobile_sdkEncryptionSessionRetrievalDetails* _Nullable retrievalDetails;
- (SealdSdkInternalsMobile_sdkActionStatusArray* _Nullable)addMultipleTmrAccesses:(SealdSdkInternalsMobile_sdkTmrRecipientWithRightsArray* _Nullable)recipients error:(NSError* _Nullable* _Nullable)error;
- (BOOL)addProxySession:(NSString* _Nullable)proxySessionId rights:(SealdSdkInternalsMobile_sdkRecipientRights* _Nullable)rights error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkActionStatusArray* _Nullable)addRecipients:(SealdSdkInternalsMobile_sdkRecipientsWithRightsArray* _Nullable)recipients error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)addTmrAccess:(SealdSdkInternalsMobile_sdkTmrRecipientWithRights* _Nullable)tmrRecipient error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkClearFile* _Nullable)decryptFile:(NSData* _Nullable)encryptedFile error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)decryptFileFromURI:(NSString* _Nullable)encryptedFileURI error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)decryptMessage:(NSString* _Nullable)clearMessage error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)encryptFile:(NSData* _Nullable)clearFile filename:(NSString* _Nullable)filename error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encryptFileFromURI:(NSString* _Nullable)clearFileURI error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)encryptMessage:(NSString* _Nullable)clearMessage error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkRevokeResult* _Nullable)revokeAll:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkRevokeResult* _Nullable)revokeOthers:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkRevokeResult* _Nullable)revokeRecipients:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)recipientsIds proxySessionsIds:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)proxySessionsIds error:(NSError* _Nullable* _Nullable)error;
@end

@interface SealdSdkInternalsMobile_sdkMobileEncryptionSessionArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSessionArray* _Nullable)add:(SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)mes;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkMobileSDK : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkConnector* _Nullable)addConnector:(NSString* _Nullable)value connectorType:(NSString* _Nullable)connectorType preValidationToken:(SealdSdkInternalsMobile_sdkPreValidationToken* _Nullable)preValidationToken error:(NSError* _Nullable* _Nullable)error;
- (BOOL)addGroupMembers:(NSString* _Nullable)groupId membersToAdd:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)membersToAdd adminsToSet:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)adminsToSet error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkCheckSigchainResponse* _Nullable)checkSigchainHash:(NSString* _Nullable)userId sigchainHash:(NSString* _Nullable)sigchainHash position:(long)position error:(NSError* _Nullable* _Nullable)error;
- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (BOOL)convertGroupTMRTemporaryKey:(NSString* _Nullable)groupId temporaryKeyId:(NSString* _Nullable)temporaryKeyId tmrJWT:(NSString* _Nullable)tmrJWT rawOverEncryptionKey:(NSData* _Nullable)rawOverEncryptionKey deleteOnConvert:(BOOL)deleteOnConvert error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConvertTmrAccessesResponse* _Nullable)convertTmrAccesses:(NSString* _Nullable)tmrJWT overEncryptionKey:(NSData* _Nullable)overEncryptionKey conversionFilters:(SealdSdkInternalsMobile_sdkTmrAccessesConvertFilters* _Nullable)conversionFilters deleteOnConvert:(BOOL)deleteOnConvert error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkAccountInfo* _Nullable)createAccount:(SealdSdkInternalsMobile_sdkCreateAccountOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)createEncryptionSession:(SealdSdkInternalsMobile_sdkRecipientsWithRightsArray* _Nullable)recipients metadata:(NSString* _Nullable)metadata useCache:(BOOL)useCache error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)createGroup:(NSString* _Nullable)groupName members:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)members admins:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)admins preGeneratedKeys:(SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable)preGeneratedKeys error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkGroupTMRTemporaryKey* _Nullable)createGroupTMRTemporaryKey:(NSString* _Nullable)groupId authFactor:(SealdSdkInternalsMobile_sdkAuthFactor* _Nullable)authFactor isAdmin:(BOOL)isAdmin rawOverEncryptionKey:(NSData* _Nullable)rawOverEncryptionKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkCreateSubIdentityResponse* _Nullable)createSubIdentity:(SealdSdkInternalsMobile_sdkCreateSubIdentityOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (BOOL)deleteGroupTMRTemporaryKey:(NSString* _Nullable)groupId temporaryKeyId:(NSString* _Nullable)temporaryKeyId error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkDevicesMissingKeysArray* _Nullable)devicesMissingKeys:(BOOL)forceLocalAccountUpdate error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)exportIdentity:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConnectorsArray* _Nullable)getConnectorsFromSealdId:(NSString* _Nullable)sealdId error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkAccountInfo* _Nullable)getCurrentAccountInfo;
- (SealdSdkInternalsMobile_sdkStringArray* _Nullable)getSealdIdsFromConnectors:(SealdSdkInternalsMobile_sdkConnectorTypeValueArray* _Nullable)connectorTypeValues error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkGetSigchainResponse* _Nullable)getSigchainHash:(NSString* _Nullable)userId position:(long)position error:(NSError* _Nullable* _Nullable)error;
- (BOOL)heartbeat:(NSError* _Nullable* _Nullable)error;
- (BOOL)importIdentity:(NSData* _Nullable)identity error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConnectorsArray* _Nullable)listConnectors:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkListedGroupTMRTemporaryKeys* _Nullable)listGroupTMRTemporaryKeys:(NSString* _Nullable)groupId page:(long)page all:(BOOL)all error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMassReencryptResponse* _Nullable)massReencrypt:(NSString* _Nullable)deviceId options:(SealdSdkInternalsMobile_sdkMassReencryptOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)prepareRenew:(SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable)preGeneratedKeys error:(NSError* _Nullable* _Nullable)error;
- (BOOL)pushJWT:(NSString* _Nullable)jwt error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConnector* _Nullable)removeConnector:(NSString* _Nullable)connectorId error:(NSError* _Nullable* _Nullable)error;
- (BOOL)removeGroupMembers:(NSString* _Nullable)groupId membersToRemove:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)membersToRemove error:(NSError* _Nullable* _Nullable)error;
- (BOOL)renewGroupKey:(NSString* _Nullable)groupId preGeneratedKeys:(SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable)preGeneratedKeys error:(NSError* _Nullable* _Nullable)error;
- (BOOL)renewKeys:(SealdSdkInternalsMobile_sdkRenewKeysOptions* _Nullable)options error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConnector* _Nullable)retrieveConnector:(NSString* _Nullable)connectorId error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)retrieveEncryptionSession:(NSString* _Nullable)messageId useCache:(BOOL)useCache lookupProxyKey:(BOOL)lookupProxyKey lookupGroupKey:(BOOL)lookupGroupKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)retrieveEncryptionSessionByTmr:(NSString* _Nullable)tmrJWT sessionId:(NSString* _Nullable)sessionId overEncryptionKey:(NSData* _Nullable)overEncryptionKey tmrAccessesFilters:(SealdSdkInternalsMobile_sdkTmrAccessesRetrievalFilters* _Nullable)tmrAccessesFilters tryIfMultiple:(BOOL)tryIfMultiple useCache:(BOOL)useCache error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)retrieveEncryptionSessionFromBytes:(NSData* _Nullable)fileBytes useCache:(BOOL)useCache lookupProxyKey:(BOOL)lookupProxyKey lookupGroupKey:(BOOL)lookupGroupKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)retrieveEncryptionSessionFromFile:(NSString* _Nullable)fileUri useCache:(BOOL)useCache lookupProxyKey:(BOOL)lookupProxyKey lookupGroupKey:(BOOL)lookupGroupKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSession* _Nullable)retrieveEncryptionSessionFromMessage:(NSString* _Nullable)message useCache:(BOOL)useCache lookupProxyKey:(BOOL)lookupProxyKey lookupGroupKey:(BOOL)lookupGroupKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkMobileEncryptionSessionArray* _Nullable)retrieveMultipleEncryptionSessions:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)sessionIds useCache:(BOOL)useCache lookupProxyKey:(BOOL)lookupProxyKey lookupGroupKey:(BOOL)lookupGroupKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkListedGroupTMRTemporaryKeys* _Nullable)searchGroupTMRTemporaryKeys:(NSString* _Nullable)groupId opts:(SealdSdkInternalsMobile_sdkSearchGroupTMRTemporaryKeysOpts* _Nullable)opts error:(NSError* _Nullable* _Nullable)error;
- (BOOL)setGroupAdmins:(NSString* _Nullable)groupId addToAdmins:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)addToAdmins removeFromAdmins:(SealdSdkInternalsMobile_sdkStringArray* _Nullable)removeFromAdmins error:(NSError* _Nullable* _Nullable)error;
- (BOOL)shouldRenewGroup:(NSString* _Nullable)groupId ret0_:(BOOL* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (BOOL)updateCurrentDevice:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkConnector* _Nullable)validateConnector:(NSString* _Nullable)connectorId challenge:(NSString* _Nullable)challenge error:(NSError* _Nullable* _Nullable)error;
@end

@interface SealdSdkInternalsMobile_sdkMobileSSKSPassword : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)changeIdentityPassword:(NSString* _Nullable)userId currentPassword:(NSString* _Nullable)currentPassword newPassword:(NSString* _Nullable)newPassword error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)retrieveIdentityFromPassword:(NSString* _Nullable)userId password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)retrieveIdentityFromRawKeys:(NSString* _Nullable)userId rawStorageKey:(NSString* _Nullable)rawStorageKey rawEncryptionKey:(NSData* _Nullable)rawEncryptionKey error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)saveIdentityFromPassword:(NSString* _Nullable)userId password:(NSString* _Nullable)password identity:(NSData* _Nullable)identity error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)saveIdentityFromRawKeys:(NSString* _Nullable)userId rawStorageKey:(NSString* _Nullable)rawStorageKey rawEncryptionKey:(NSData* _Nullable)rawEncryptionKey identity:(NSData* _Nullable)identity error:(NSError* _Nullable* _Nullable)error;
@end

@interface SealdSdkInternalsMobile_sdkMobileSSKSTMR : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkGetFactorTokenResponse* _Nullable)getFactorToken:(NSString* _Nullable)sessionId authFactor:(SealdSdkInternalsMobile_sdkAuthFactor* _Nullable)authFactor challenge:(NSString* _Nullable)challenge error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkRetrieveIdentityResponse* _Nullable)retrieveIdentity:(NSString* _Nullable)sessionId authFactor:(SealdSdkInternalsMobile_sdkAuthFactor* _Nullable)authFactor challenge:(NSString* _Nullable)challenge rawTMRSymKey:(NSData* _Nullable)rawTMRSymKey error:(NSError* _Nullable* _Nullable)error;
- (SealdSdkInternalsMobile_sdkSaveIdentityResponse* _Nullable)saveIdentity:(NSString* _Nullable)sessionId authFactor:(SealdSdkInternalsMobile_sdkAuthFactor* _Nullable)authFactor challenge:(NSString* _Nullable)challenge rawTMRSymKey:(NSData* _Nullable)rawTMRSymKey identity:(NSData* _Nullable)identity error:(NSError* _Nullable* _Nullable)error;
@end

@interface SealdSdkInternalsMobile_sdkPreGeneratedKeys : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull encryptionKey;
@property (nonatomic) NSString* _Nonnull signingKey;
@end

@interface SealdSdkInternalsMobile_sdkPreValidationToken : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull domainValidationKeyId;
@property (nonatomic) NSString* _Nonnull nonce;
@property (nonatomic) NSString* _Nonnull token;
@end

@interface SealdSdkInternalsMobile_sdkRecipientRights : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL read;
@property (nonatomic) BOOL revoke;
@property (nonatomic) BOOL forward;
@end

@interface SealdSdkInternalsMobile_sdkRecipientWithRights : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull recipientId;
@property (nonatomic) SealdSdkInternalsMobile_sdkRecipientRights* _Nullable rights;
@end

@interface SealdSdkInternalsMobile_sdkRecipientsWithRightsArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkRecipientsWithRightsArray* _Nullable)add:(SealdSdkInternalsMobile_sdkRecipientWithRights* _Nullable)s;
- (SealdSdkInternalsMobile_sdkRecipientWithRights* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkRenewKeysOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t expireAfter;
@property (nonatomic) SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable preGeneratedKeys;
@property (nonatomic) NSData* _Nullable preparedRenewal;
@end

@interface SealdSdkInternalsMobile_sdkRetrieveIdentityResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable identity;
@property (nonatomic) BOOL shouldRenewKey;
@property (nonatomic) NSString* _Nonnull authenticatedSessionId;
@end

@interface SealdSdkInternalsMobile_sdkRevokeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) SealdSdkInternalsMobile_sdkActionStatusArray* _Nullable recipients;
@property (nonatomic) SealdSdkInternalsMobile_sdkActionStatusArray* _Nullable proxySessions;
@end

@interface SealdSdkInternalsMobile_sdkSaveIdentityResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ssksId;
@property (nonatomic) NSString* _Nonnull authenticatedSessionId;
@end

@interface SealdSdkInternalsMobile_sdkSdkInitializeOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull apiURL;
@property (nonatomic) NSString* _Nonnull appId;
@property (nonatomic) long keySize;
@property (nonatomic) NSString* _Nonnull databasePath;
@property (nonatomic) NSData* _Nullable databaseEncryptionKey;
@property (nonatomic) int64_t encryptionSessionCacheTTL;
@property (nonatomic) int8_t logLevel;
@property (nonatomic) BOOL logNoColor;
@property (nonatomic) NSString* _Nonnull instanceName;
@property (nonatomic) NSString* _Nonnull platform;
@end

@interface SealdSdkInternalsMobile_sdkSearchGroupTMRTemporaryKeysOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull groupId;
@property (nonatomic) long page;
@property (nonatomic) BOOL all;
@end

@interface SealdSdkInternalsMobile_sdkSsksPasswordInitializeOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ssksURL;
@property (nonatomic) NSString* _Nonnull appId;
@property (nonatomic) int8_t logLevel;
@property (nonatomic) BOOL logNoColor;
@property (nonatomic) NSString* _Nonnull instanceName;
@property (nonatomic) NSString* _Nonnull platform;
@end

@interface SealdSdkInternalsMobile_sdkSsksTMRInitializeOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ssksURL;
@property (nonatomic) NSString* _Nonnull appId;
@property (nonatomic) int8_t logLevel;
@property (nonatomic) BOOL logNoColor;
@property (nonatomic) NSString* _Nonnull instanceName;
@property (nonatomic) NSString* _Nonnull platform;
@end

@interface SealdSdkInternalsMobile_sdkStringArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkStringArray* _Nullable)add:(NSString* _Nullable)s;
- (NSString* _Nonnull)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdkTmrAccessesConvertFilters : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull sessionId;
@property (nonatomic) NSString* _Nonnull createdById;
@property (nonatomic) NSString* _Nonnull tmrAccessId;
@end

@interface SealdSdkInternalsMobile_sdkTmrAccessesRetrievalFilters : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull createdById;
@property (nonatomic) NSString* _Nonnull tmrAccessId;
@end

@interface SealdSdkInternalsMobile_sdkTmrRecipientWithRights : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) SealdSdkInternalsMobile_sdkAuthFactor* _Nullable authFactor;
@property (nonatomic) SealdSdkInternalsMobile_sdkRecipientRights* _Nullable rights;
@property (nonatomic) NSData* _Nullable overEncryptionKey;
@end

@interface SealdSdkInternalsMobile_sdkTmrRecipientWithRightsArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (SealdSdkInternalsMobile_sdkTmrRecipientWithRightsArray* _Nullable)add:(SealdSdkInternalsMobile_sdkTmrRecipientWithRights* _Nullable)s;
- (SealdSdkInternalsMobile_sdkTmrRecipientWithRights* _Nullable)get:(long)i;
- (long)size;
@end

@interface SealdSdkInternalsMobile_sdk : NSObject
// skipped variable ErrorFileDbInvalidKeyLength with unsupported type: github.com/seald/go-seald-sdk/utils.SealdError

// skipped variable ErrorFileDbRequiresEncKeyMobile with unsupported type: github.com/seald/go-seald-sdk/utils.SealdError

@end

FOUNDATION_EXPORT SealdSdkInternalsMobile_sdkMobileSDK* _Nullable SealdSdkInternalsMobile_sdkInitialize(SealdSdkInternalsMobile_sdkSdkInitializeOptions* _Nullable options, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT SealdSdkInternalsMobile_sdkMobileSSKSPassword* _Nullable SealdSdkInternalsMobile_sdkNewSSKSPasswordPlugin(SealdSdkInternalsMobile_sdkSsksPasswordInitializeOptions* _Nullable options);

FOUNDATION_EXPORT SealdSdkInternalsMobile_sdkMobileSSKSTMR* _Nullable SealdSdkInternalsMobile_sdkNewSSKSTMRPlugin(SealdSdkInternalsMobile_sdkSsksTMRInitializeOptions* _Nullable options);

FOUNDATION_EXPORT NSString* _Nonnull SealdSdkInternalsMobile_sdkParseSessionIdFromBytes(NSData* _Nullable fileBytes, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull SealdSdkInternalsMobile_sdkParseSessionIdFromFile(NSString* _Nullable encryptedFilePath, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull SealdSdkInternalsMobile_sdkParseSessionIdFromMessage(NSString* _Nullable message, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT SealdSdkInternalsMobile_sdkPreGeneratedKeys* _Nullable SealdSdkInternalsMobile_sdkPreGeneratedKeysFromPKCS1DER(NSData* _Nullable encryptionKey, NSData* _Nullable signingKey, NSError* _Nullable* _Nullable error);

#endif
