
// Objective-C API for talking to the following Go packages
//
//	go-seald-sdk/mobile_sdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SealdSdkInternals_FRAMEWORK_H__
#define __SealdSdkInternals_FRAMEWORK_H__

#include "SealdSdkInternalsMobile_sdk.objc.h"
#include "Universe.objc.h"

#endif
